### ISSUE TITLE
The `guest-entries` tag pair disrupts array augmentation

### ISSUE THREAD

**Issue by danielfowler** [duncanmcclean/guest-entries#77]
### Description

In my templates from a v2 site, I've been wondering why on earth my tag pairs for a `Users` fieldtype are not dynamically augmenting user data as [promised in the Statamic docs](https://statamic.dev/fieldtypes/users#templating). Worse, I sometimes see it working and sometimes not which complicates my confusion.

I finally figured out that when my tag pairs exist *inside* a `guest-entries` tag pair, they lose the augmentation.

For example, in a collection entry I have:

```YAML
staff:
  - f5edb239-8c26-44a6-8b55-c602debe9ec5
  - fc8f37ba-812f-46b5-903a-c171e386800e
  - a93542df-83ca-4ab0-82c1-47db7df9f4c5
```

Powered by this blueprint:

```YAML
      -
        handle: staff
        field:
          type: users
          display: Staff
          instructions: 'Staff you designate will have all the same abilities as you, except access to the billing for your annual subscription.'
          label: '{{ first_name }} {{ last_name }} ({{ email }})'
          width: 50
          mode: tags
```

I'm logged in as the first user in that array. For the template I have:

```Antlers
<p>{{ staff }}{{ id | truncate(5) }}:{{ first_name ?? name }} ... {{ /staff }}</p>

{{ guest-entries:update collection="studios" :id="page:id" redirect="{ current_uri }?success=ownership_saved" }}
  <p>{{ staff }}{{ id | truncate(5) }}:{{ first_name ?? name }} ... {{ /staff }}</p>
{{ /guest-entries:update }}
```

And it renders as:

```HTML
<p>f5edb:Sir ... fc8f3:Daniel ... a9354:Dan Chasemore ... </p>
<form method="POST" action="https://cast98eu.test/!/guest-entries/update">
  <!-- tokenized inputs hidden -->
  <p>f5edb:Sir ... f5edb:Sir ... f5edb:Sir ... </p>
</form>
```

When I `dump` inside the tag pair, it looks like the values are being rendered as simple strings. 

```PHP
"value" => "a93542df-83ca-4ab0-82c1-47db7df9f4c5"
```
```PHP
  "staff" => array:3 [▼
    0 => "f5edb239-8c26-44a6-8b55-c602debe9ec5"
    1 => "fc8f37ba-812f-46b5-903a-c171e386800e"
    2 => "a93542df-83ca-4ab0-82c1-47db7df9f4c5"
  ]
```

I can get it working if I wrap individual array values with `{{ user:profile }}`.

### Steps to reproduce

1. Create a Users fieldtype in a collection blueprint
2. Add some users to the array
3. Call the array tag pair within a `guest-entries` form

### Environment

Environment
Application Name: Cast98
Laravel Version: 11.36.0
PHP Version: 8.3.14
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: cast98eu.test
Maintenance Mode: OFF
Timezone: America/New_York
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 2
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.43.0 PRO

Statamic Addons
duncanmcclean/guest-entries: 4.2.0
statamic/migrator: dev-master
